Fixed molecule init scenario (#2419)
Avoid error like below:

  File ".../site-packages/click/types.py", line 149, in get_metavar
    return '[%s]' % '|'.join(self.choices)
TypeError: sequence item 0: expected str instance, <DriverClass> found

This adopts the same code from init-role which was working correctly.

Signed-off-by: Sorin Sbarnea <ssbarnea@redhat.com>