Update dependency.py (#868)
Type was causing command "molecule dependency" to fail.

```
# molecule dependency
ERROR: Scenario 'defalt' not found.  Exiting.
```