Extend Git clone depth (#1756)
As explained in the following review:

    https://github.com/ansible/molecule/pull/1755#pullrequestreview-205294580

Because we have not made a release in a long time, the logic that `pbr`
uses to generate a prerelease version has broken (because it cannot
count beyond 100 due a performance optimisation we have made). By
extending this number, we will not be getting the dreaded error we were
seeing when trying to run a test.pypi.org upload:

    HTTPError: 400 Client Error: File already exists.

Closes https://github.com/ansible/molecule/issues/1730.

Signed-off-by: Luke Murphy <lukewm@riseup.net>