Document and hint logger.py (#4305)
The decorators are a bit more complex here than in state.py, so we need
a slightly more complicated hint.

_Ideally_, we would be able to use `Callable[Concatenate[HasConfig, P],
R]` and not have to fish the `HasConfig` out of `args`, but there are
some complicated issues with wrapped functions (see
https://github.com/python/typeshed/issues/10653 for more context):

```
error: Incompatible return value type (got "_Wrapped[[HasConfig, **P], R, [HasConfig, **P], R]", expected "Callable[[HasConfig, **P], R]")  [return-value]
```

---------

Co-authored-by: Sorin Sbarnea <ssbarnea@redhat.com>