Remove use of tox-venv (#2120)
tox-venv seems to cause some weird issues on Travis and its use only on
CI makes testing diverge from normal usage.

Avoid exception below which happened after tox-venv was installed:
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'tox_venv'

Signed-off-by: Sorin Sbarnea <ssbarnea@redhat.com>