Update schema_v2.py
Platforms_base_schema destroy copy.deepcopy(base_schema). Then when validating multiply molecules it's running with errors. Eg. two moleule with different drivers. One Azure second docker . If docker will be validated first from it schema we are getting 
 'image': {
                    'type': 'string',
which is not valid for azure driver but will be in schema. 
ERROR: Failed to validate.
{'platforms': [{0: [{'image': ['must be of string type']}], 1: [{'image': ['must be of string type']}], 2: [{'image': ['must be of string type']}]}]}

Moving platforms_base_schema to base_schema and changing the util.merge_dicts fixes the issue.