fix: allow to use stdin/out
Fixes #3435

Use of ansible runtime prevents of use interactive stdin/stdout,
and lack of split causing traces like this:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/env /bin/podman exec -e COLUMNS=254 -e LINES=60 -e TERM=bash -e TERM=xterm -ti mariadb_104 bash'
(because molecule tries to run whole command line as binary name
without arguments).

Signed-off-by: George Shuklin <george.shuklin@gmail.com>